### ISSUE TITLE
unit test failures

### ISSUE THREAD

**Issue by danmarsden** [microsoft/moodle-theme_boost_o365teams#1]
showing this on 3.5 branch but I suspect all branches are affected - looks like the amd files weren't built normally.

There was 1 failure:

1) core_requirejs_testcase::test_requirejs
Failed asserting that '/var/www/html/theme/boost_o365teams/amd/build/iframeChecker.js' contains ".min".

/var/www/html/lib/tests/requirejs_test.php:91
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "core_requirejs_testcase" lib/tests/requirejs_test.php

**Comment by pramithkm** [comment]
Any update on this?? Starting to receive this on 3.7 Stable branch with version 3.7.0.0.

**Comment by kristian-94** [comment]
I am also getting these unit test failures. Should be just minifying of the javascript that is needed

**Comment by kristian-94** [comment]
@weilai-irl  could you please review this? thanks!

**Comment by weilai-irl** [comment]
Hi all,

I'll include fix to this in the next release.

Thanks.
Lai

**Comment by danmarsden** [comment]
any updates on the next release? - this is still an issue with the master branch - just needs someone to run grunt properly on the branch - should be an easy fix.
https://docs.moodle.org/dev/Grunt

**Comment by weilai-irl** [comment]
Hi @danmarsden, 

The fix to the issue has been included in the latest release of the plugin for Moodle 3.7, 3.8 and 3.9. Thank you for reporting the issue.

I'll close the issue now.

Regards,
Lai
