### ISSUE TITLE
using teams in browser theme is applied over default theme

### ISSUE THREAD

**Issue by mnods** [microsoft/moodle-theme_boost_o365teams#3]
Hi just testing this for potential use
using mdl 3.9 with 3.9 branch
when using teams in browser, added moodle tab, boost_o365 theme applied in teams ok but when I return to moodle in browser tab, the o365 theme is applied over the default (currently fordson)
any config or tweaking I can apply to avoid this?
cheers

**Comment by weilai-irl** [comment]
Hi @mnods,

If you use Teams web app in browser to access Moodle from the Teams tab, the theme will be applied in session, so all subsequent access to the Moodle site in the same session will be using the theme set in the session. This is a known limitation to the integration, and so far we don't have a solution to it.

On a separate note, issues about the plugin should be reported at https://github.com/microsoft/o365-moodle/issues (in fact, this exact issue has been reported before at https://github.com/microsoft/o365-moodle/issues/1278). I'll close issues options in this repo.

Regards,
Lai
